DROP TABLE IF EXISTS STATE CASCADE;
DROP TABLE IF EXISTS COLOR CASCADE;
DROP TABLE IF EXISTS TEAM CASCADE;
DROP TABLE IF EXISTS PLAYER CASCADE;

CREATE TABLE STATE(
    STATE_ID SERIAL,
    NAME VARCHAR(256),
    PRIMARY KEY (STATE_ID)
);

CREATE TABLE COLOR(
    COLOR_ID SERIAL,
    NAME VARCHAR(256),
    PRIMARY KEY (COLOR_ID)
);

CREATE TABLE TEAM(
    TEAM_ID SERIAL,
    NAME VARCHAR(256),
    STATE_ID INT,
    COLOR_ID INT,
    WINS INT,
    LOSSES INT,
    PRIMARY KEY (TEAM_ID),
    FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID),
    FOREIGN KEY (COLOR_ID) REFERENCES COLOR(COLOR_ID)
);


CREATE TABLE PLAYER(
  PLAYER_ID SERIAL,
  TEAM_ID INT,
  UNIFORM_NUM INT,
  FIRST_NAME VARCHAR(256),
  LAST_NAME VARCHAR(256),
  MPG INT,
  PPG INT,
  RPG INT,
  APG INT,
  SPG DECIMAL(2,1),
  BPG DECIMAL(2,1),
  PRIMARY KEY (PLAYER_ID),
  FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);
